
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc0ODAwNTg1","is_bot":false,"login":"AlexLim-Pro","name":"Alex Lim"},"headRefName":"Alex-RecommendationRequest","number":58,"title":"Alex recommendation request","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/58"},{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"Bharat-ArticleTable","number":56,"title":"Article table","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/56"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"Ritu-HelpRequestController","number":55,"title":"Ritu help request controller written, tests written and passed","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/55"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"Kyle-UCSBDiningCommonsMenuItem-DELETE-Endpoint","number":54,"title":"Implemented DELETE Endpoint for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/54"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"Kyle-UCSBDiningCommonsMenuItem-Put","number":53,"title":"Implemented PUT endpoint for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/53"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"Kyle-UCSBDiningCommonsMenuItem-Get-By-Id","number":52,"title":"Implemented get by ID for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/52"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-UCSBOrg","number":51,"title":"Rohan ucsb org","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/51"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"Kyle-UCSBDiningCommonsMenuItem-Controller-And-Post","number":50,"title":"Added Controller and implemented get and post endpoints for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/50"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"Ritu-HelpRequestTable","number":47,"title":"created database table for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-2/pull/47"}]
